# -*- coding: utf-8 -*-
"""nltk_utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XIDZhYjJ2J3XhWVgUQMfWbXygG0HumPt
"""

# from google.colab import drive

# drive.mount('/content/grive')

import nltk
nltk.download('punkt')

import numpy as np

from nltk.stem.porter import PorterStemmer

stemmer= PorterStemmer()

def tokenize(sentence):
    return nltk.word_tokenize(sentence)

def stem(word):
    return stemmer.stem(word.lower())

def bag_of_words(tokenized_sentence, all_words):
    tokenized_sentence= [stem(w) for w in tokenized_sentence]
    bag= np.zeros(len(all_words))
    for idx, w in enumerate(all_words):
        if w in tokenized_sentence:
            bag[idx]=1
        
    return bag


